name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Node.js and LocalTunnel
      run: |
        choco install nodejs
        npm install -g localtunnel
    - name: Create Tunnel
      run: |
        lt --port 3389 > localtunnel_url.txt &
        Start-Sleep -s 10  # Wait for the tunnel to be established
    - name: Display Tunnel URL
      run: |
        cat localtunnel_url.txt
