name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/localtunnel/localtunnel/archive/refs/tags/2.0.0.zip -OutFile localtunnel.zip
    - name: Extract
      run: Expand-Archive localtunnel.zip
    - name: Install Node.js
      run: |
        choco install nodejs
        refreshenv
    - name: Install LocalTunnel
      run: npm install -g ./localtunnel-2.0.0
    - name: Create Tunnel
      run: |
        lt --port 3389 > localtunnel_url.txt &
        Start-Sleep -s 10  # Wait for the tunnel to be established
    - name: Display Tunnel URL
      run: |
        cat localtunnel_url.txt
