name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Install Node.js and LocalTunnel
      run: |
        choco install nodejs
        npm install -g localtunnel
    - name: Create Tunnel
      run: |
        lt --port 3389 > localtunnel_url.txt &
        Start-Sleep -s 10  # Wait for the tunnel to be established
    - name: Display Tunnel URL
      run: |
        cat localtunnel_url.txt
